1h axe diggles
namidaka/itembalancing pull request #101
Opened 2022-11-22 19:05 UTC by Diggles27

2022-11-23 14:51 UTC, namidaka requested changes

2022-11-23 14:51 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_peasant_pickaxe_1_t1_blade" name="{=aPr8NPdo}Western Iron Polearm Head" tier="1" piece_type="Blade" mesh="axe_craft_37_head" distance_to_next_piece="10.4" distance_to_previo
Please keep the convention for weight : .877 -> 0.877

2022-11-23 14:51 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_peasant_hatchet_1_t1_blade" name="{=KhHXgQJb}Common Wrought Iron Axe Head" tier="1" piece_type="Blade" mesh="axe_craft_32_head" distance_to_next_piece="4.3" distance_to_prev
Please keep the convention for weight

2022-11-24 04:39 UTC, Diggles27 commented
did not do the sickle, its not an axe! :)

2022-11-24 10:44 UTC, namidaka approved these changes

2022-11-24 10:44 UTC, merged