changes based from feedback
namidaka/itembalancing pull request #128
Opened 2022-11-27 04:35 UTC by AngryMob010

Following got some minor speed increase edits:
Engraved Backsword
Lion Imprinted Saber
Decorated Arming Sword

also Winds Fury was completely changed. The name doesn't make it clear to people that it is a cavalry sword, resulting in confusion about its stats. so i changed it back to a normal weapon.

2022-11-27 15:03 UTC, namidaka requested changes
No. 107 Length 89 speed is a big no. I'm already adding 13% to swing speed.
This weapon is going to be awful

2022-11-28 02:40 UTC, namidaka requested changes

2022-11-28 02:40 UTC, namidaka commented on items.json
> +        "swingSpeed": 89
lower either swing speed or length

2022-11-28 02:40 UTC, namidaka commented on items.json
> +        "swingSpeed": 89
lower swing speed or length

2022-11-29 23:13 UTC, AngryMob010 commented
gonna cancel this. these weapons are being reworked as part of a different branch fixing lengths/speeds according to the notes made in discord

2022-11-29 23:13 UTC, closed without merging