Added thrust to Long Bardiche and Hafted Mace
namidaka/itembalancing pull request #147
Opened 2022-11-29 22:58 UTC by MaxParks

2022-11-30 12:28 UTC, namidaka requested changes

2022-11-30 12:28 UTC, namidaka commented on crafting_pieces.xml
>    <CraftingPiece id="crpg_long_bardiche_head" name="{=}Long Bardiche Head" tier="4" piece_type="Blade" mesh="axe_craft_16_head" distance_to_next_piece="28.8" distance_to_previous_piece="6" weight="0.
items.json?

2022-11-30 14:53 UTC, MaxParks commented on crafting_pieces.xml
>    <CraftingPiece id="crpg_long_bardiche_head" name="{=}Long Bardiche Head" tier="4" piece_type="Blade" mesh="axe_craft_16_head" distance_to_next_piece="28.8" distance_to_previous_piece="6" weight="0.
Done added it

2022-12-02 18:11 UTC, namidaka approved these changes

2022-12-02 18:11 UTC, merged