1h sword aserai edits
namidaka/itembalancing pull request #22
Opened 2022-11-15 20:53 UTC by Truthful33

(FIX) Edited the following items. Fixed stab values based on feedback:

- crpg_aserai_noble_sword_1_t5 | Decorated Kaskara
- crpg_aserai_noble_sword_2_t5 | Decorated Long Scimitar
- crpg_aserai_noble_sword_3_t5 | Decorated Scimitar with Wide Grip
- crpg_aserai_noble_sword_4_t5 | Engraved Angular Kaskara
- crpg_aserai_sword_1_t2 | Iron Flyssa
- crpg_aserai_sword_2_t2 | Iron Scimitar
- crpg_aserai_sword_3_t3 | Slightly Ridged Flyssa
- crpg_aserai_sword_4_t4 | Fine Steel Long Kaskara
- crpg_aserai_sword_5_t4 | Long Fine Steel Scimitar
- crpg_aserai_sword_6_t4 | Narrow Fine Steel Kaskara
- crpg_aserai_sword_7_t5 | Thamaskene Steel Kaskara

Find additional details [here](https://docs.google.com/spreadsheets/d/1sTt6PEGD3EHn-EBzABQRszbdwDkoSAa765WSm8Vb5JE/edit#gid=1341011737) (Aserai Changes).

2022-11-15 22:11 UTC, namidaka requested changes

2022-11-15 22:11 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_aserai_noble_sword_1_t5_blade" name="{=gwkR6TZL}Decorated Kaskara Blade" tier="5" piece_type="Blade" mesh="aserai_noble_blade_2" culture="Culture.aserai" length="93.2" weigh
.7 -> 0.7

2022-11-15 22:11 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_aserai_noble_sword_2_t5_blade" name="{=T1xFTaOf}Decorated Long Scimitar Blade" tier="5" piece_type="Blade" mesh="aserai_noble_blade_1" culture="Culture.aserai" length="90" w
.75 -> 0.75

2022-11-15 22:11 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_aserai_noble_sword_4_t5_blade" name="{=RdVX1jC0}Engraved Kaskara Blade" tier="5" piece_type="Blade" mesh="aserai_noble_blade_3" culture="Culture.aserai" length="71" weight="
.79 -> 0.79

2022-11-15 22:51 UTC, Truthful33 commented
Committed the changes

2022-11-15 23:51 UTC, namidaka requested changes

2022-11-15 23:51 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_aserai_noble_sword_3_t5_blade" name="{=xYgJN0Ja}Decorated Scimitar Blade" tier="5" piece_type="Blade" mesh="aserai_noble_blade_4" culture="Culture.aserai" length="87.4" weig
.75-> 0.75

2022-11-15 23:57 UTC, Truthful33 commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_aserai_noble_sword_3_t5_blade" name="{=xYgJN0Ja}Decorated Scimitar Blade" tier="5" piece_type="Blade" mesh="aserai_noble_blade_4" culture="Culture.aserai" length="87.4" weig
committed

2022-11-16 02:27 UTC, namidaka approved these changes

2022-11-16 02:27 UTC, merged