Heirloom spears
namidaka/itembalancing pull request #303
Opened 2023-05-29 14:18 UTC by Muparadzi

Updated the following spears, loosely following the pattern below:-

+1 (+1 speed)
+2 (+1 damage)
+3 (+1 speed)

Simple pike
Iron Pitchfork 
Pitchfork 
Wide Leaf Spear
Fine Steel Hewing Spear
Fine Pike
Hoplite Spear

2023-05-29 14:33 UTC, namidaka requested changes
Keep on the good work

2023-05-29 15:36 UTC, Muparadzi commented
2h spears completed, continuing with 1h now

2023-05-29 17:12 UTC, namidaka requested changes

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "flags": [],
A little bit weak. Consider adding 1 damage or 1 speed.

2023-05-29 17:12 UTC, namidaka commented on items.json
> +    "requirement": 0,
Same here +1 damage or speed

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "flags": [],
Original Tier was 5.81 , this one probably requires a considerable buff

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "requirement": 0,
consider adding one stats on this one too

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "flags": [],
original tier is 9.7 , h1 is a little bit too weak. Try to get at least tier 9

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "flags": [],
Try adding one stat. I'd rather have it tier 10.1 (going slightly over tier 10) then losing 0.7 tier

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "requirement": 0,
opriginal tier was 9.74 , it's a bit too weak. Try not to get heirloomed version further than 1 tier. 0.8/0.7 is acceptable

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "requirement": 0,
If you have to choose between 9.1 and 10.1 , i'd rather go slightly overboard

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "flags": [],
same here .

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "requirement": 0,
same here, original tier was 7.04

2023-05-29 17:12 UTC, namidaka commented on items.json
>      "flags": [],
same here , original tier was 9.8

2023-05-30 08:22 UTC, Muparadzi commented
I have addressed comments regarding tier of items

2023-05-30 18:19 UTC, namidaka approved these changes

2023-05-30 18:19 UTC, merged