Throwing.new items.july2023
namidaka/itembalancing pull request #332
Opened 2023-07-17 06:48 UTC by Diggles27

2023-07-17 15:13 UTC, namidaka requested changes
Shuriken should have a low tier version a mid tier version and a high tier one.

2023-07-19 05:52 UTC, Diggles27 commented
made throwing knives/daggers consistent. Knife = cut, Dagger = pierce

2023-07-19 10:40 UTC, namidaka requested changes

2023-07-19 10:40 UTC, namidaka commented on items/weapons.xml
> +  <CraftedItem id="crpg_highland_throwing_dagger_h2" name="{Diggles}Steel Throwing Knife +2" crafting_template="crpg_ThrowingKnife" culture="Culture.battania" modifier_group="knife_throwing">
v2

2023-07-19 19:09 UTC, Diggles27 commented on items/weapons.xml
> +  <CraftedItem id="crpg_highland_throwing_dagger_h2" name="{Diggles}Steel Throwing Knife +2" crafting_template="crpg_ThrowingKnife" culture="Culture.battania" modifier_group="knife_throwing">
fix submitted

2023-07-20 14:03 UTC, namidaka approved these changes

2023-07-20 14:03 UTC, merged