Hoplite.update.DEC2023
namidaka/itembalancing pull request #436
Opened 2023-12-12 06:26 UTC by Diggles27

Hoplite.update.DEC2023
•	Renamed Short Milita Spear to Hasta Spear
•	Converted Fine Steel Leaf Spear to CUT damage only and renamed to Leaf Bladed Spear (community request)
  o	T8 – 2h mode: 167 L, 32c 86 spd swing, 23c 94 spd thrust
  o	T8 – 1h mode: 86 spd thrust
•	Converted 3x 4d spears back to 2d for more hoplite choices
  o	Narrow Long Headed renamed to Narrow Headed Long Spear
      	T6, 1H mode: 179 L, 89 spd, 26 pierce
  o	Simple Short Spear to Militia Short Spear
      	T2 – 1H mode: 146 L, 92 spd, 24 pierce
  o	Tall Tipped Long Spear
      	T7 – 1H mode: 199 L, 88 spd, 26 pierce
•	All altered items refunded except Short Militia Spear (rename only)

2023-12-23 23:28 UTC, namidaka requested changes

2023-12-23 23:28 UTC, namidaka commented on items.json
>          "bodyArmor": 0,
How does that lead to more diversity , when you're just removing an extra optional mode?!

2023-12-23 23:28 UTC, namidaka commented on items.json
> -      {
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -        "swingDamageType": "Blunt",
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -        "swingDamage": 16,
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -        "swingDamage": 16,
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -      {
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -      {
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -        "itemUsage": "polearm_block_long_shield_thrust",
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -          "NotUsableWithOneHand",
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -      {
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -        "class": "TwoHandedPolearm",
same

2023-12-23 23:28 UTC, namidaka commented on items.json
> -        "class": "TwoHandedPolearm",
same

2023-12-23 23:30 UTC, namidaka requested changes

2023-12-23 23:30 UTC, namidaka commented on items.json
>          "bodyArmor": 0,
also you removed the 2D mode not the 4d...
Currently this spear has in 2h mode : 4d and 2d. You just removed one mod? 
Are you like trying to nerf or make unfun specific classes on purpose?
If you continue going completely against the design philosophy of item balancing despite me telling you repeatedly to stop doing it , i'm going to start denying pull request on sight

2024-03-09 17:41 UTC, Yeldur commented
Converting PR to draft as not ready for further review

2024-05-20 09:26 UTC, Muparadzi commented
No update in 5 months.

2024-05-20 09:26 UTC, closed without merging