1h Maces General Speed Reduction
namidaka/itembalancing pull request #455
Opened 2024-03-11 21:49 UTC by Telfordski

Work in Progress

https://docs.google.com/spreadsheets/d/1UsgIDQG861FlnY_wKnLKQfcSnu2zxiNp1x2k6bIIGb4/edit#gid=2132882987

2024-03-14 13:16 UTC, Yeldur commented
Converting to draft as not ready for review yet

2024-03-14 15:55 UTC, Telfordski commented
> Converting to draft as not ready for review yet

ty should have it done by end of week

2024-04-18 18:31 UTC, Telfordski commented
> Converting to draft as not ready for review yet

Think that's done. Finally.

2024-04-19 21:39 UTC, Yeldur requested changes
There are a few changes that need to be made but the glaring issue right now is primarily that this change results in massive tier reductions across the board for 1h mace but does not offer anything to tier-match them to their old tiers.

What we do want is for speed to be reduced

What we don't want is to have zero high tier maces, which this change would seemingly enforce based on what I can see from the changes.

General rule of thumb I would say is that super high speed maces like 88+ speed are super fast and should receive a speed reduction **BUT** be given damage in return for their lost speed to ensure that tier changes are not major.

I've added three review points marked as:
"example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically." to give an example of some items that shouldn't really see a speed reduction - There ARE more examples of this though and will need you to address them before approval.

TL;DR

Where we reduce stats, we should increase others to ensure that tier does not change drastically

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_steel_flanged_mace_v3_h0" name="{=fz23ajFz}Steel Flanged Mace" crafting_template="crpg_Mace" culture="Culture.khuzait" modifier_group="mace">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_steel_flanged_mace_v3_h1" name="{=fz23ajFz}Steel Flanged Mace +1" crafting_template="crpg_Mace" culture="Culture.khuzait" modifier_group="mace">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_steel_flanged_mace_v3_h2" name="{=fz23ajFz}Steel Flanged Mace +2" crafting_template="crpg_Mace" culture="Culture.khuzait" modifier_group="mace">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_steel_flanged_mace_v3_h3" name="{=fz23ajFz}Steel Flanged Mace +3" crafting_template="crpg_Mace" culture="Culture.khuzait" modifier_group="mace">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_heavy_flanged_mace_v3_h0" name="{=mzvtFPPi}Heavy Flanged Mace" crafting_template="crpg_Mace" is_merchandise="false">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_heavy_flanged_mace_v3_h1" name="{=mzvtFPPi}Heavy Flanged Mace +1" crafting_template="crpg_Mace" is_merchandise="false">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_heavy_flanged_mace_v3_h2" name="{=mzvtFPPi}Heavy Flanged Mace +2" crafting_template="crpg_Mace" is_merchandise="false">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_heavy_flanged_mace_v3_h3" name="{=mzvtFPPi}Heavy Flanged Mace +3" crafting_template="crpg_Mace" is_merchandise="false">
Should go to v2 not v3

2024-04-19 21:39 UTC, Yeldur commented on items.json
> +    "id": "crpg_arabian_mace_v2_h0",
No stat changes, this shouldn't be refunded

2024-04-19 21:39 UTC, Yeldur commented on items.json
> +    "tier": 7.60975,
Tier reduction, needs a refund

2024-04-19 21:39 UTC, Yeldur commented on items.json
> +    "id": "crpg_military_hammer_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:39 UTC, Yeldur commented on items.json
> +    "id": "crpg_militia_pernach_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:39 UTC, Yeldur commented on items.json
> +    "id": "crpg_long_pernach_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur requested changes
Cont from above

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "tier": 6.763587,
speed reduction is OK but should be offset by an increase in damage to match tiers

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "tier": 7.35880756,
speed reduction is OK but should be offset by an increase in damage to match tiers

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "tier": 6.09928036,
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_fine_steel_mace_v2_h3",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_fullered_western_mace_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_heavy_horsemans_mace_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_judgement_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_knights_fall_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_long_cavalry_mace_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_medium_goedendag_v2_h0",
speed reduction is OK but should be offset by an increase in damage to match tiers

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_onehanded_barmace_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_onehanded_gada_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_persian_steel_mace_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_spiralled_mace_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_steppe_spiked_mace_v2_h0",
speed reduction is OK but should be offset by an increase in damage to match tiers

2024-04-19 21:53 UTC, Yeldur commented on items.json
> +    "id": "crpg_warhammer_v2_h0",
example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically.

2024-04-19 22:27 UTC, Yeldur commented
Following discussion am moving this back to draft temporarily whilst discussion is had with balance team over maces.

2024-04-22 15:45 UTC, Telfordski commented
> There are a few changes that need to be made but the glaring issue right now is primarily that this change results in massive tier reductions across the board for 1h mace but does not offer anything to tier-match them to their old tiers.
> 
> What we do want is for speed to be reduced
> 
> What we don't want is to have zero high tier maces, which this change would seemingly enforce based on what I can see from the changes.
> 
> General rule of thumb I would say is that super high speed maces like 88+ speed are super fast and should receive a speed reduction **BUT** be given damage in return for their lost speed to ensure that tier changes are not major.
> 
> I've added a few points marked as: "example of an item that does not need a speed reduction but if wanted, needs to be offset by an increase in other areas to ensure tier does not change too drastically." to give an example of some items that shouldn't really see a speed reduction.
> 
> TL;DR
> 
> Where we reduce stats, we should increase others to ensure that tier does not change drastically

that's just like your opinion man - at least I assume that's what you're basing the assessments of these reductions on, for the ones you passed comment.

I don't want to match their old tiers, or swap damage for speed; I want to reduce the speed of the maces I reduced - based on their damage and length and overall options available. I want to reduce the speed, for the damage and length they have already - feel free to tweak them yourself / rebuff or revert afterwards if you think the nerfs were unwelcome, but let's quickly sort out this budget adjustment at least, because no-one can really assess shit with these broken ass numbers - like some crazy scientist I can create some absolutely broken unfathomable shit, and it's my own assessments and testing that have prevented that instead of the budget system - even that said, some are still potentially too fast, but I want to experiment with handling more first before any more changes. Most of the maces available are fairly high tier options (at least tier 8 in terms of meta), because I'm a shit crafter who just wants to make viable ass options for everyone with good trade-offs. If the budget correction isn't perfect, so be it, perhaps it can be weighted more towards speed, but fundamentally it must be adapted and I think the current set of maces (although I'm biased) are a good place to start because I've made them at their perceived limits.

2025-01-04 23:04 UTC, Yeldur commented
Closing as budget changes have since come in to adjust 1h blunt rendering this PR null & void

2025-01-04 23:04 UTC, closed without merging