2D polearm swing/thrust
namidaka/itembalancing pull request #469
Opened 2024-03-29 17:31 UTC by Erdertus

Second attempt at adding polearm 2D mode for swing over head and thrust only.

2024-04-01 19:06 UTC, Yeldur requested changes
refund required for each tier

2024-04-01 19:06 UTC, Yeldur commented on items/weapons.xml
> +  <CraftedItem id="crpg_english_bill_v1_h0" name="{=Salt}English Bill" crafting_template="crpg_Polearm_2dswing">
refund required

2024-04-01 19:13 UTC, Meowkov approved these changes
This is looking fine by me and should in theory work.
Worst case we disable the items :D

2024-04-02 12:47 UTC, Yeldur approved these changes
Approved, falls in line with changes we want to make to enable 2D weapons

2024-04-06 16:43 UTC, merged