Meow Voulges
namidaka/itembalancing pull request #476
Opened 2024-04-24 21:17 UTC by Meowkov

Added Ancient Long Voulge
Added Fabulous Voulge

2024-05-07 10:17 UTC, Meowkov reviewed
Looking good, approved.

2024-05-07 11:31 UTC, Yeldur approved these changes
Approving on Meow's behalf

2024-05-09 19:26 UTC, Erdertus submitted a review, later dismissed
BvS with reduction in cut damage to balance the tier - visual consistency with the rest of the weapons.

You can dismiss this change if you want though.

2024-05-11 23:43 UTC, Yeldur commented
> BvS with reduction in cut damage to balance the tier - visual consistency with the rest of the weapons.
> 
> You can dismiss this change if you want though.

You be the boss of poles, I shall update them like so milord - Will resubmit once done 🫡

2024-05-20 09:26 UTC, Erdertus approved these changes

2024-05-20 12:04 UTC, Muparadzi requested changes

2024-05-20 12:04 UTC, Muparadzi commented on items.json
> +    "requirement": 3,
needs removing

2024-05-20 13:20 UTC, Meowkov commented on items.json
> +    "requirement": 3,
done :D

2024-05-20 13:33 UTC, Muparadzi approved these changes

2024-05-25 18:19 UTC, Yeldur approved these changes
After double checking things with Meow and testing myself, I'm happy - Approving

2024-05-25 18:20 UTC, merged