Initial Commit Small Hammer
namidaka/itembalancing pull request #477
Opened 2024-04-24 21:45 UTC by Meowkov

Added Small Hammer

2024-05-07 10:15 UTC, Meowkov reviewed
Looking good.
Approved on my end.
Hammerssassins go!

2024-05-07 11:31 UTC, Yeldur submitted a review, later dismissed
Approving on Meow's behalf

2024-05-09 19:32 UTC, Erdertus requested changes
+3 tier is too high. If it's a struggle to make it fit because presumably dropping weight is costing a lot at this point, maybe just drop the +0 to T9 or something.

2024-05-11 23:06 UTC, Yeldur commented
> +3 tier is too high. If it's a struggle to make it fit because presumably dropping weight is costing a lot at this point, maybe just drop the +0 to T9 or something.

I disagree that +3 is too high, it's 10.2, barely over t10 and gains +1 damage which is _all_ it gains at +3 - This is a minor increase overall. Lowering to t9 makes no logical sense simply because +3 goes a marginal amount over the line.

2024-05-18 16:25 UTC, Yeldur commented
Discussed tiers within IB team and made decision of allowing up to t10.2 without justification, as a result resubmitting review request

2024-05-20 07:46 UTC, Muparadzi requested changes

2024-05-20 07:46 UTC, Muparadzi commented on items.json
> +    "requirement": 18,
Remove these changes whilst we wait for #473 to be resolved.

2024-05-20 09:17 UTC, Muparadzi approved these changes

2024-05-20 09:23 UTC, Erdertus approved these changes

2024-05-25 18:19 UTC, Yeldur submitted a review, later dismissed
After double checking things with Meow and testing myself, I'm happy - Approving

2024-05-25 18:21 UTC, Yeldur commented
Rebase required following merge of https://github.com/namidaka/itembalancing/pull/476

2024-05-25 18:51 UTC, Yeldur approved these changes
rebase should have added the xbow changes as they are part of current master branch -> issues resolved -> approved

2024-05-25 18:51 UTC, merged