Reduce current brig over gambeson body armor
namidaka/itembalancing pull request #497
Opened 2024-06-23 18:30 UTC by AppleTruce

change (color) Brigandine with Armpads body armor from 52 to 40
change (color) Brigandine body armor from 52 to 40
fix spelling mistake "Bed brigandine" to "**R**ed Brigandine"

Reduced the body armor for brigandines that only have cloth garments underneath brigandine.  This will allow lighter armor classes to also wear brigandines if they like and looks more consistent with armor values for simple chest armor.  Will add brigandines with mail underneath, that will fill the 52 body armor space these brigandines used to be in.  Top tier for brigandines is still brigandine over mail with besagews.  Distinction between mail, or gambeson underneath brigandine will serve as a strong visual que to players about relative armor strengths.

2024-06-23 22:26 UTC, AppleTruce commented
This may be made redundant by the final pull request about re-balancing brigandines.  This may also be included in the 3 pull requests I made to add items, that was unintentional, but I think I know how I messed that up now.

2024-07-22 10:28 UTC, Meowkov approved these changes
XMLs looking good.

2024-12-02 15:59 UTC, Erdertus requested changes
@AppleTruce Duplicates PR 500 / 501 again

2024-12-03 19:57 UTC, Erdertus approved these changes
Approved with caveat duplicated in other PRs, merge numerically

2024-12-15 22:48 UTC, closed without merging