Updated Lances to all be couchable and adjusted Light Lance to no lon…
namidaka/itembalancing pull request #57
Opened 2022-11-18 01:21 UTC by Senesar

Adjusted all items named with "Lance" to be couchable, and removed Bracing from Light Lance as it was an outlier among the class.

2022-11-18 01:45 UTC, namidaka requested changes

2022-11-18 01:45 UTC, namidaka commented on items.json
> +        "itemUsage": "polearm_couch",
Update as radical as this should be discussed with me prior. Couches are particularly problematic to cRPG, as we cannot modify the mechanics (cooldown , maximum rotational angles ,  collision detection) . I'd probably want to have a few very long couchable lances that you have to drop when you're finished with and that have moderate amount of damage

2022-11-18 01:45 UTC, namidaka commented on items.json
> +        "itemUsage": "polearm_couch",
![image](https://user-images.githubusercontent.com/47090987/202597623-6887659d-e0c2-42c5-bda2-53a65cc980d4.png)

2022-11-19 03:30 UTC, Senesar commented
Closing, created alternate request

2022-11-19 03:30 UTC, closed without merging