1h Swords Battania update to new tiers
namidaka/itembalancing pull request #58
Opened 2022-11-18 02:01 UTC by AngryMob010

All battania 1h swords given a thorough rebalance with new tier formula

Engraved Backsword
Decorated Broadsword
Highland Broad Blade
Broad Ridged Shortsword renamed to Fine Steel Broad Shortsword to fit in the lineup of broadswords better
Highland Fine Steel Blade renamed to Highland Highland Pointed Blade to indicate thrust specialty
Fine Steel Cavalry Broadsword
Broadsword renamed to Steel Broadsword to fit in the lineup of broadswords better
Ridged Iron Broadsword

2022-11-18 02:52 UTC, namidaka requested changes

2022-11-18 02:52 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_battania_noble_sword_2_t5_pommel" name="{=BKHKQ15N}Turqouise Pommel" tier="5" piece_type="Pommel" mesh="battania_pommel_8" culture="Culture.battania" length="2.5" weight="0.
1 gram pommel?

2022-11-18 02:52 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_battania_noble_sword_2_t5_handle" name="{=SqR5K74b}Fine Highland Grip" tier="4" piece_type="Handle" mesh="battania_grip_1" culture="Culture.battania" length="15.5" weight="0
1 gram handle?

2022-11-18 02:52 UTC, namidaka commented on crafting_pieces.xml
> +  <CraftingPiece id="crpg_battania_noble_sword_2_t5_guard" name="{=DLvSnz8U}Etched Highland Guard" tier="5" piece_type="Guard" mesh="battania_guard_5" culture="Culture.battania" length="5.7" weight="
1 gram guard?

2022-11-18 04:10 UTC, AngryMob010 commented
adjusted the 1 gram parts to 10 grams.

it is intentional for them to be very low values overall. was the only way to make the thrust speed high while keeping swing speed low.

2022-11-20 04:24 UTC, namidaka approved these changes

2022-11-20 04:24 UTC, merged