Update Light Rider/Cav/Plane Lance to new standard
namidaka/itembalancing pull request #65
Opened 2022-11-19 03:32 UTC by Senesar

Namidaka — Yesterday at 11:22 PM
remove couchable from all lance.
Change the scale factor of 2 or 3 lances to make the length something between 250 and 280. Make sure they have low thrust speed and low damage (maybe 18 damage?). Give them couch 

Update Light Lance, Light Steppe Rider Lance, Light Cavalry Lance to 250-280 range, provided couching, and 17p. Remove dcouching from rest of lances.

2022-11-19 18:21 UTC, Senesar commented
3x lances were updated per request and couch was cleared from rest

2022-11-20 01:33 UTC, namidaka requested changes

2022-11-20 01:33 UTC, namidaka commented on crafting_pieces.xml
> +      <Thrust damage_type="Pierce" damage_factor="1.735" />
17.35 damage. Please have only integer damage . so 
damage_factor="1.735" -> damage_factor="1.7"

2022-11-20 01:33 UTC, namidaka commented on items.json
>    },
This one has no couch

2022-11-20 01:33 UTC, namidaka commented on items.json
>    },
Where are the rest of the lances?

2022-11-27 02:12 UTC, closed without merging